# nothing

name: Today Status Check
# daily job
on:
  push:
  workflow_dispatch:
  schedule:
    - # daily job at 01:00 with  UTC time
      cron: "0 1 * * 1-5"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    env:
      FNG_MIN: ${{ secrets.FNG_MIN }}
      FNG_MAX: ${{ secrets.FNG_MAX }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2 # using the workflow with default settings
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Preparing
        run: |
          npm install --global yarn && yarn install
      - name: Execute
        run: |
          node .
